// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Seed runs outside Next via tsx (server-only libs can't be imported here).
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations / introspection run over the DIRECT (unpooled) connection —
    // Prisma Migrate cannot run through Neon's PgBouncer pooler. The app's
    // runtime queries use DATABASE_URL (pooled) via the Neon adapter instead.
    url: process.env["DIRECT_URL"],
  },
});
